---
apiVersion: v1
kind: ReplicationController
metadata:
  name: dind-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
      - name: daemon
        image: docker:stable-dind
        securityContext:
          privileged: true
        args: 
        - --authorization-plugin=authz
        ports:
          - containerPort: 2375
            name: docker
            protocol: TCP
        volumeMounts:
        - name: authz-socket
          mountPath: /run/docker/plugins
      - name: authz
        image: enieuw/docker-authz
        volumeMounts:
        - name: authz-socket
          mountPath: /app/socket
      volumes:
      - name: authz-socket
        emptyDir:
---
kind: Service
apiVersion: v1
metadata:
 name: docker
 labels:
   app: docker
spec:
  ports:
    - port: 2375
      protocol: TCP
      targetPort: 2375
  selector:
    app: docker
